import PersonalInfo from './PersonalInfo'

function Experience({ experience }) {
  return (
    <section>
      <h2>Work Experience</h2>
      {experience.map((job, index) => (
        <div key={index} style={{marginTop: '3rem'}}>
          <h3>{job.title} at {job.employer}</h3>
          <p>{job.period}</p>
          <p><em>{job.sector}</em></p>
          <ul>
            {job.responsibilities.map((r, i) => <li key={i}>{r}</li>)}
          </ul>
          <p>Working language: {job.workingLanguage}</p>
          <p><strong>Tech stack:</strong> {job.technicalStack.join(', ')}</p>
        </div>
      ))}
    </section>
  )
}

function CV({ data, metadata, mode }) {
  console.log(metadata);

  return (
    <>
      <div className="watermark">{mode === 'pdf' ? 'Generated by Puppeteer' : 'Implemented in Vibe Coding'}</div>
      {mode === 'html' && <a href="/cv.pdf" className="download-link" download>Download PDF</a>}
      <PersonalInfo personalInfo={data.personalInfo} mode={mode} />
      <hr className="section-divider" />
      <Experience experience={data.experience} />
    </>
  )
}

export default CV
