import HeaderBar from './HeaderBar'
import PersonalInfo from './PersonalInfo'

function Education({ language, metadata, education }) {
  return (
    <section>
      <h2>{metadata[language]}</h2>
      {education.map((edu, index) => (
        <div key={index} style={{marginTop: '3rem'}}>
          <h3>{edu.degree} – {edu.school}</h3>
          <p>{edu.period}</p>
          <p><strong>{metadata.children.subjects[language]}:</strong> {edu.subjects}</p>
        </div>
      ))}
    </section>
  )
}

function Experience({ language, metadata, experience }) {
  return (
    <section>
      <h2>{metadata[language]}</h2>
      {experience.map((job, index) => (
        <div key={index} style={{marginTop: '3rem'}}>
          <h3>{job.title} at {job.employer}</h3>
          <p>{job.period}</p>
          <p><em>{job.sector}</em></p>
          <ul>
            {job.responsibilities.map((r, i) => <li key={i}>{r}</li>)}
          </ul>
          <p><strong>{metadata.children.workingLanguage[language]}:</strong> {job.workingLanguage}</p>
          <p><strong>{metadata.children.technicalStack[language]}:</strong> {job.technicalStack.join(', ')}</p>
        </div>
      ))}
    </section>
  )
}

function CV({ data, metadata, mode }) {
  return (
    <>
      <div className="watermark">{mode === 'pdf' ? 'Generated by Puppeteer' : 'Implemented in Vibe Coding'}</div>
      <HeaderBar mode={mode} />
      <PersonalInfo language={data.language} metadata={metadata.personalInfo} personalInfo={data.personalInfo} mode={mode} />
      <hr className="section-divider" />
      <Experience language={data.language} metadata={metadata.experience} experience={data.experience} />
      <hr className="section-divider" />
      <Education language={data.language} metadata={metadata.education} education={data.education} />
    </>
  )
}

export default CV
