import PersonalInfo from './PersonalInfo'
import Experience from './Experience'

function CV({ json, mode }) {
  return (
    <>
      <div className="watermark">{mode === 'pdf' ? 'Generated by Puppeteer' : 'Implemented in Vibe Coding'}</div>
      {mode === 'html' && <a href="/cv.pdf" className="download-link" download>Download PDF</a>}
      <PersonalInfo personalInfo={json.personalInfo} mode={mode} />
      <hr className="section-divider" />
      <Experience experience={json.experience} />
    </>
  )
}

export default CV
